### ISSUE TITLE
can not use

### ISSUE THREAD

**Issue by barnett2010** [augenblick/Blender_DarkSouls_Import#1]
![image](https://user-images.githubusercontent.com/8305408/55384059-4422e300-555c-11e9-8719-aab5af443e1d.png)
![2019-04-02_152920](https://user-images.githubusercontent.com/8305408/55384079-51d86880-555c-11e9-94fc-eeb2ec5f038a.jpg)
![2019-04-02_152913](https://user-images.githubusercontent.com/8305408/55384085-543ac280-555c-11e9-9129-beed821255e7.jpg)
![image](https://user-images.githubusercontent.com/8305408/55384102-5f8dee00-555c-11e9-925b-f7848f89840d.png)

**Comment by augenblick** [comment]
This issue is caused by the default directories not being set.  In the current version, these default paths must be defined by setting the add-on preferences.
