### ISSUE TITLE
Currently does not work

### ISSUE THREAD

**Issue by Nezara** [augenblick/Blender_DarkSouls_Import#2]
Will not work on blender 2.79 nor is even visible as an addon for blender 2.81. 

Hope this is eventually updated with a fix. its really awesome work.

**Comment by augenblick** [comment]
Nezara, thank you for the feedback.  I have plans to eventually jump back to this and update it to work with Blender 2.8x (as well as other updates).  I don't know exactly when I'll make time for these updates though.

**Comment by augenblick** [comment]
I've updated the add-on to function in Blender 2.8x.  If you end up checking it out, let me know if you encounter any issues.
