### ISSUE TITLE
Create Milestone

### ISSUE THREAD

**Issue by aaronaskew** [augenblick/Blender_DarkSouls_Import#8]
Was thinking it'd be nice to have a milestone established for the overhaul. Not sure if you have a versioning scheme in mind, but maybe we could call the milestone Version 0.x.1. 

Also, we could list out the broad goals. 
- Refactor code for maintainability
- Fix missing/incorrect texture issues
- Others?

Thoughts?

**Comment by augenblick** [comment]
Yeah, this is a great idea.  I've got some goals in mind-- we can discuss to prioritize and decide which make it into the 0.2.1 version.

You've definitely listed the top priorities for 0.2.1.  Refactoring and Fixing the texture issue.  

There are a couple of other small quality-of-life improvements that we could probably include, and possibly get import of vertex normals working as well.

**Comment by aaronaskew** [comment]
Done.
